### PR TITLE
Linux and gcc adaptations

### PR DESCRIPTION
**Pull request by szubersk**
Few small adaptations for Linux:

ability to compile the project with g++ 7
FASTBUILD_TEMP_PATH is respected on Linux systems
gcc/g++ requires preprocessed files to have *.i extension to operate correctly
gcc compiler type will be detected if binary name is in a form "gcc-${version}" e. g. gcc-7

### CODE REVIEW

**Comment by szubersk** [comment]
@ffulin Please let me know what you think about changes above

File: Code/Core/Mem/MemDebug.cpp [hunk 1]
```diff
@@ -9,6 +9,10 @@
 
 #if defined( MEM_DEBUG_ENABLED )
 
+#if defined( __GNUC__ ) && __GNUC__ >= 7
+    #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
+#endif
+
```
Comment (ffulin) [inline Code/Core/Mem/MemDebug.cpp]: I think we might be better off just changing the one switch statement the flags this so that we don't need to turn it off, potentially covering up other instances of this warning in this cpp and other cpp files in the library when it is built in Unity.

File: Code/Tools/FBuild/FBuildCore/FBuild.cpp [hunk 2]
```diff
@@ -742,28 +742,32 @@ bool FBuild::DisplayDependencyDB( const Array< AString > & targets ) const
 //------------------------------------------------------------------------------
 /*static*/ bool FBuild::GetTempDir( AString & outTempDir )
 {
-    #if defined( __WINDOWS__ )
+    #if defined( __WINDOWS__ ) || defined( __LINUX__ )
```
Comment (ffulin) [inline Code/Tools/FBuild/FBuildCore/FBuild.cpp]: This is a good fix. It looks like we can actually apply the same logic on OSX as well.

File: Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp [hunk 3]
```diff
@@ -2021,6 +2021,10 @@ bool ObjectNode::WriteTmpFile( Job * job, AString & tmpDirectory, AString & tmpF
 
     FileStream tmpFile;
     AStackString<> fileName( sourceFile->GetName().FindLast( NATIVE_SLASH ) + 1 );
+    if (GetFlag( FLAG_GCC ))
+    {
+       fileName += ".i";
+    }
```
Comment (ffulin) [inline Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp]: Can you tell me a bit about what problems you had with this?  FASTBuild is built with gcc on Linux and I've not encountered this problem (though i have seen this in the past). It would be good to ensure we have test coverage for any case that requires this.

File: Code/fbuild.bff [hunk 4]
```diff
@@ -38,11 +38,11 @@ Compiler( 'Compiler-x64Clang' )
 }
 Compiler( 'Compiler-x64-Linux' )
 {
```
Comment (ffulin) [inline Code/fbuild.bff]: In the future, I'd like to extend the config files for Linux so that you can easily switch between versions, but for now, given that it's not going to be the right version for everyone, I think I'd prefer to keep this at v4.9 since that is the version I use to make official releases.

**Comment by ffulin** [comment]
Thanks for the changes. I've added some comments to the various files.

File: Code/Core/Mem/MemDebug.cpp (hunk 1 above)
Comment (szubersk) [reply Code/Core/Mem/MemDebug.cpp]: Corrected. I'll upload next iteration soon

File: Code/Tools/FBuild/FBuildCore/FBuild.cpp (hunk 2 above)
Comment (szubersk) [reply Code/Tools/FBuild/FBuildCore/FBuild.cpp]: Applied for __APPLE__ too. I think __APPLE__ is more reliable define than __OSX__.

File: Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp (hunk 3 above)
Comment (szubersk) [reply Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp]: The problem here is strictly connected to g++ being unable to distinguish between cpp file and preprocessed cpp file when file extension is .cpp. If it's the case then some defines automagically inserted by g++ at the beginning of the file (compiler defaults) are mistreated as regular macro definitions causing compilation to fail. The fix is to help compiler detect file content by adding proper extension (*.i). Seems like g++ 7 on my laptop is unaffected by this but on my friends machine it was a clear error (g++ 5.3.x if I remember correctly). I don't think this can be covered by unit testing though. The change is not harmful in any way and it works perfectly on g++ 7 and 5.3.x.

File: Code/fbuild.bff (hunk 4 above)
Comment (szubersk) [reply Code/fbuild.bff]: Noted on g++ version. The binary name needs to be changed though because invocation of gcc implies good-old C code in the file, not C++ code which causes compilation errors. As with *.i extension - some gcc version might or might not detect the proper language based on file content. It's safer to clearly force C++ mode - saves nerves.

**Comment by szubersk** [comment]
@ffulin Thank you very much for reviewing my changes. I uploaded newest revision addressing your concerns.

File: Code/fbuild.bff [hunk 5]
```diff
@@ -38,7 +38,7 @@ Compiler( 'Compiler-x64Clang' )
...
-    .Executable     = '/usr/bin/gcc'
+    .Executable     = '/usr/bin/g++'
```
Comment (dummyunit) [inline Code/fbuild.bff]: This change will result in .c files being compiled as C++. In case of LZ4/xxHash (which are bundled with FASTBuild) this doesn't lead to new errors or warnings, but it might change code generation (for better or worse).

**Comment by dummyunit** [comment]
> Failed due to missing file: /home/szubersk/projects/fastbuild/Code/BFFFuzzer-x64Linux-Debug

BFFFuzzer can be compiled only in 2 configurations, but there in no way (in current configs) to exclude a specific project from `All-*` aliases in some configurations.

This error is my fault essentially, I've added BFFFuzzer, but still didn't find a nice solution for this error. In my personal branch I currently use an ugly workaround for it: https://github.com/dummyunit/fastbuild/commit/b3116df72c9ea9b0359d010a4793d5670df2359e#diff-dcd73127757265333744a09bdb3ef30bR57 I don't think that it is acceptable for inclusion if official sources though.

File: Code/fbuild.bff (hunk 5 above)
Comment (szubersk) [reply Code/fbuild.bff]: Is there a way to define 2 different compilers, one for C and the other one for C++ code?

Comment (ffulin) [reply Code/fbuild.bff]: It is possible to define two compilers by having two Compiler() sections in the bff. However, a simpler way is to keep the same compiler and to specify the language on the command line with the -x option.

Comment (szubersk) [reply Code/fbuild.bff]: I reverted this change and gcc-7 and gcc-8 seem to work OK. No point in forcing g++.

**Comment by szubersk** [comment]
@dummyunit 
@ffulin 
I addressed all comments and either corrected or reverted changes.

File: Code/Core/Mem/MemDebug.cpp [hunk 6]
```diff
@@ -40,12 +40,20 @@ void MemDebug::FillMem( void * ptr, const size_t size, const uint32_t pattern )
                             (char)( ( pattern & 0x00FF0000 ) >> 16 ) };
         const char * b = bytes;
         char * cit = static_cast< char * >( static_cast< void * >( it ) );
+
+        #if defined( __GNUC__ ) && __GNUC__ >= 7
+            #pragma GCC diagnostic push
+            #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
+        #endif
```
Comment (ffulin) [inline Code/Core/Mem/MemDebug.cpp]: This switch statement has now been changed so this warning disabling is no longer required: https://github.com/fastbuild/fastbuild/commit/68e5e7dc88774d63dd6c81f67b2ae64b7570f565

File: Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp (hunk 3 above)
Comment (ffulin) [reply Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp]: I am using gcc 4.9.2 and am not seeing this problem. I wonder if it's how gcc is being invoked that is the problem - in all my cases, i'm compiling with: ```/<path>/gcc -std=c++11``` Can you tell me what args you are using, and if possible if this makes a difference on your version(s)?

If this is the issue, it would be nice to make this just work with a better preprocessed file extension along the lines of what you have proposed, but I think we need to detect .c vs .cpp and use .i or .ii respectively to be correct.

**Comment by ffulin** [comment]
I've integrated these changes. They will be part of the next release (v0.98). Thanks for the fixes!
